version: '3'

name: delivery-panel

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=dockerPass
      - POSTGRESQL_DATABASE=delivery-panel
